import React from "react";
import { Box } from "@material-ui/core";

export const InfoTextCostOfCapital = () => {
  return (
    <>
      <Box>
        <b>Unlevered beta</b> - (a.k.a. Asset Beta) measures the market risk of
        the company without the impact of debt.
      </Box>
      <Box>
        <b>Levered beta</b> - (a.k.a. equity beta) is a measure of market risk
        and determines how much risk comes with owning a stock.
      </Box>
      <Box>
        <b>Riskfree Rate</b> - refers to the theoretical rate of return of an
        investment with zero risk.
      </Box>
      <Box>
        <b>Country Equity Risk Premium</b> - defined as the additional returns
        expected by the investor in order to assume the risk of investing in
        foreign markets as compared to the domestic country.
      </Box>
      <Box>
        <b>Mature Market Equity Risk Premium</b> - the return demanded by an
        investor for a stable market (such as the U.S) when they invest in the
        stock market over a risk-free rate.
      </Box>
      <Box>
        <b>Marginal Tax Rate</b> - the tax rate paid on the next dollar of
        income.
      </Box>
      <Box>
        <b>Effective Tax Rate</b> - the percent of their income that an
        individual or a corporation pays in taxes.
      </Box>
    </>
  );
};

export const InfoTextValueDrivingInputs = () => {
  return (
    <>
      <Box>
        <b>Compound annual growth rate (CAGR)</b> - the rate of return that
        would be required for an investment to grow from its beginning balance
        to its ending balance, assuming the profits were reinvested at the end
        of each year of the investment's lifespan.
      </Box>
      <Box>
        <b>Earnings Before Interest and Taxes (EBIT)</b> - an indicator of a
        company's profitability. It's used to analyze the performance of a
        company's core operations without the costs of the capital structure and
        tax expenses impacting profit.
      </Box>
      <Box>
        <b>Year of Convergence</b> - the movement in the price of a futures
        contract toward the spot or cash price of the underlying commodity over
        time.
      </Box>
      <Box>
        <b>Sales to Capital Ratio</b> - a liquidity and activity ratio
        indicating the amount of money from sales, generated by a dollar of
        working capital investment. In other words, a ratio measuring the
        efficiency of company's working capital utilization in order to generate
        the certain level of sales.
      </Box>
      <Box>
        <b>Pre-tax Cost of Debt</b> - the rate a company pays on its debt, such
        as bonds and loans. The key difference between the cost of debt and the
        pre-tax cost of debt is the fact that interest expense is taken before
        tax-deductible.
      </Box>
    </>
  );
};

export const InfoTextNormalDebt = () => {
  return (
    <>
      <Box>
        <b>Average Maturity of Debt</b> - the weighted average of all the
        current maturities of the debt securities held in the fund.
      </Box>
    </>
  );
};

export const InfoTextConvertibleDebt = () => {
  return (
    <>
      <Box>
        <b>Book Value of Convertible Debt</b> -
      </Box>
      <Box>
        <b>Interest Expense on Convertible Debt</b> -
      </Box>
      <Box>
        <b>Maturity of Convertible Debt</b> - indicates the date when the note
        is due to be repaid to the investor along with any accrued interest, if
        it has not yet converted to equity.
      </Box>
    </>
  );
};

export const InfoTextPreferredStock = () => {
  return (
    <>
      <Box>
        <b>Number of Preferred Shares</b> - are shares of a company’s stock with
        dividends that are paid out to shareholders before common stock
        dividends are issued.
      </Box>
      <Box>
        <b>Market Price Per Share</b> - used to describe how much an asset or
        company is worth in a financial market.
      </Box>
      <Box>
        <b>Annual Dividend Per Share</b> - a cash distribution by a company to
        its shareholders. It's also an important financial ratio in
        understanding the financial health and long-term growth prospects of a
        company.
      </Box>
    </>
  );
};
