const fields = [
  'code',
  'type',
  'name',
  'exchange',
  'currencyCode',
  'currencyName',
  'currencySymbol',
  'countryName',
  'countryISO',
  'ISIN',
  'CUSIP',
  'CIK',
  'employerIdNumber',
  'fiscalYearEnd',
  'IPODate',
  'internationalDomestic',
  'sector',
  'industry',
  'gicSector',
  'gicGroup',
  'gicIndustry',
  'gicSubIndustry',
  'homeCategory',
  'isDelisted',
  'description',
  'address',
  'addressData',
  'listings',
  'officers',
  'phone',
  'webURL',
  'logoURL',
  'fullTimeEmployees',
  'updatedAt'
]

export default fields
